version: '3.3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=nickjohs

  web:
    build: .
    volumes:
      - .:/home/docker
      - box:/home/docker/box
    ports:
      - 5000:5000
    depends_on:
      - db
    command: scripts/start.sh
      
volumes:
  box:

