development:
  host: db
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: nickjohs
  password: 

test:
  host: db
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: nickjohs
  password:
